apiVersion: v1
kind: Service
metadata:
  labels:
    name: node
    role: service
  name: grafana
spec:
  type: LoadBalancer 
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30603
  selector:
    grafana: "true"
