apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment 
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
        grafana: "true"
    spec:
      containers:
        - image: grafana/grafana
          name: grafana
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 3000
