apiVersion: v1
kind: Service
metadata:
  labels:
    name: node
    role: service
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana-server
  type: LoadBalancer 
  ports:
    - port: 8080
      targetPort: 3000 
      nodePort: 30001
