apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRTnVOV2ZvVmxTSXZ1bFpKMks2UXRuVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlReU9HVTBaR0ZrTVMwek16UXpMVFJpWkRFdFlqSmxNUzFoWWpSbU9XUTJNelZsTXpBdwpIaGNOTWpBd01qSTFNakF6TnpFNFdoY05NalV3TWpJek1qRXpOekU0V2pBdk1TMHdLd1lEVlFRREV5UXlPR1UwClpHRmtNUzB6TXpRekxUUmlaREV0WWpKbE1TMWhZalJtT1dRMk16VmxNekF3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM0dDBJNFR6RlRsRSs4dmFCOEYwNzZib3FUYUQyYi9WdFZicEYyM3liWgpmYnhyUTVJWG9TbGJiMFhwUE5VRmNCVVFXdm5xQmZEMW4yRjd0dVhiQUF0MDVZQzYyMjZXaHVWdXB6UlV6aEVGCk1QbythVVpTeWFrYmtpS2IzZmdaOG5lL2cyRWdOQ2tWa1VBMk9kUkxudmhTSzdWWmgraDh0NGNUZDdBZXJQRjYKQXFMVjdXd0MzMlhrZkZDNjV3cXlXN3B6MDBZZ3VnVlJZSkVXU2FrRm9aVklVTzl6OHJWQXJlY3hGRFg1bGlCYgpjYUQzbjUydFZ2YWZhZDV5ZVpkSEViOWhwVkpxM0tkVWVNS29IcFFrNWx6VnllTFJlUDkrQis0N2J4cy9VZlBnCnJhN0JUVjA3RlFtbEUzM2lNMDlmY01hRmYrUHRiOGhhS0piNi9xdFFhdmdyQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCagpZQjhIQjF6ajlZdkJJK25WT0ZrY1AyVS8rbmNwS3o5QUUxM2Nwb2FULzNTT0xSWnpCUnMvR05hZHFpRi81UlhHCkltNk9yYTY5SkdXTlY4TWJCT0luMjJxQlJDVmZZZEdiTTdIb3k0Yk1tQUZUOVNGRmQzSkxEaTZ4c2NDNWZMUWkKSU41TDFpTmRWSVFMbDBjZW9RUDlQNWIxUW9QT0wwbktwVlFoTE9VUWM2VlRXY1ErWlBQRHRLV0JoR0FqRVVvOQpUbngrRytqbTNYVlh5VVJWWlIwbCtoOFQzSEw0MVNOY05ZcmZQeVN3My9PaHpzNVlIWmFnbjdBdVBNQlVkci9TCkdLWUxtSHhlYUxrZDhYdFhCQVF0ZS9hdmYrMUdYUCtSTlNSN1Y5aVR5cDFDWFAySGVDZE55L0xpL1M1MjI1WE4KKzlWaTlRaE8wN09UNTFQM09QNFkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://35.189.80.43
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABvweomyUKWskRjCR6EiQWle5KH8Jv1lfgKs1QG_lgHbjVJZDfkEnM8cJ26YRLoEqHT_rF28MkECQh08tPs01HCuBgusRfHw1CV8A7FzzWZ77rgdDfUvBHEb0MivqEwTo353JhnMM51xST80Ufkb6y8VKOhga49aSQSNi6xd4kRYQj9BB-V5Mgb8EFjF9LrlDc
        expiry: "2020-02-25T23:43:59.826433053Z"
      name: gcp
