apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUpBb1FXaU1uZ3pPQTZiOUNHQ0ZKdll3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05EazVZalJsTVRVdFpXUm1aUzAwWXpSbExXRXhZall0TWpCaU5UQXlaRGxqWm1VMApNQjRYRFRJd01ESXlOVEV4TVRrd00xb1hEVEkxTURJeU16RXlNVGt3TTFvd0x6RXRNQ3NHQTFVRUF4TWtORGs1CllqUmxNVFV0WldSbVpTMDBZelJsTFdFeFlqWXRNakJpTlRBeVpEbGpabVUwTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMXliT2tkS3RZZzZVTGxyMi9QdzVrdVRWMkxrankxTlVCb0dHeDZrVgpKNTExOXI1aVRQQmw5WVpLaFpSVWo5cWY5TldYejNHRTJ5dTF1dFRmR1I2MlBLSDZweHlGREIzV0ZrTTBxZGd5ClpSU3pVS2VuOVdYRkF5eExib2Q0ZkRqYzZRWi9JSnZxQzlPRUJPbExSTVBHcWdvZ0orNTM4RWRtMGwvdUdBTGwKZkxjemIyVTFTeXJvL09UdW9VVEM4bWpEYnhUWnBDZ2lUTFduVzU3eVdLV2NqTlJjSjVLNjFyaHVUY1ZZdElEWgpHaEppUlprb3grZUhzZTBvRGFpcGx3WGl4TlVQRTBjTzl5Wlh4R3p1bGJmbmZ0R3hlVmI4Y0pVZGZJK2VxSG0wCndKWW9yQXI5TEpHK2tnbTFQNlRCNms5UjBXNVdCQi9pZzJQUlhJSW1NTnF6a3dJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpTWXNhT1hSbTl5TjNwZWhua3hLZUg3Zk5uSzRzdEdRejU5UDRncndacXFrbGk5Szd5alM4ZGRNTVFoZHJxd2xTCnkxSkxvZkJuZkZpZy93U2NHR1lLdG1hLzdMY0hJQk9TVHl5WEx2OEhVdElweStGR3ZkdFFnWVgxdHZ3TzFrZVYKZFBIbzB4Yk5KSjBpTEdHZDNIS3JvejRYaVJ3aVJPcmZHQnNyemE1M0tPdEtqeHRaVzlpdjRDUTJwVm9LeTJKRApYeXJONXZ5VmxCK2tNc3p0NndBWGoyOE1vNmtyZmhYQ1Y2WkNsbFdDUGhpZERBTU1RTE5oTDZLU3J2SUJuTk53CmhIUGZyVHBkd3ZUcUM2WExWdVlac2Z4eS9pdWNTT3N5Z05DaGxXMGdPVWdXNkNEUk81TTdjN3NHT0puSFN2U0MKUWpGLzBybkhIUWtkeDV2VXl1SEVHZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.246.93.196
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABvwdxLvkB7ebKAEFLoTufgtXJJjCUX1JAbjLS3JjigNT3pNiVpzIG637yxN8BoONN1NbGJkf_6_-fVqk-n7Vk3SyJqYHOkJ7TgZtxZKkWBesm3TwKmNy3MJSd70dADuZVi7Zd_o-pY9AsJOzT6kG2Y-9fE5F7Kzf4JmN1dXBIbPvhOm80XPcD3Nm6PUSFm55p
        expiry: "2020-02-25T17:39:01.232925034Z"
      name: gcp
