---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus-config.yaml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
    - job_name: kafka
      # TODO - auto-configure: annotations
      static_configs:
      - targets: ['internal-service-0.kafka.svc.cluster.local:32500', 'internal-service-1.kafka.svc.cluster.local:32501', 'internal-service-2.kafka.svc.cluster.local:32502']

